SELECT
AdGroupId, 
aName AdGroupName
FROM (SELECT 
AdGroupId, 
LAST_VALUE(AdGroupName) OVER(PARTITION BY AdGroupId order by _PARTITIONTIME asc ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) aName
FROM {{var('t_adGroup')}}
GROUP BY 1, _PARTITIONTIME, AdGroupName)
GROUP BY 1, 2
ORDER BY 1 DESC